### ISSUE TITLE
Intense kampe virker ikke altid som de skal...

### ISSUE THREAD

**Issue by tarcom** [tarcom/NykreditBF#2]
Nogle gange står der at en kamp er intense, men points bliver ikke fordelt som intense

**Comment by tarcom** [comment]
output from selenium test:

hejsa med digsa
Starting ChromeDriver 2.23.409699 (49b0fa931cda1caad0ae15b7d1b68004acd05129) on port 39459
Only local connections are allowed.
doTestCycle enter
isIntense=true
initPointsMap={alsk=-2, dwp=3, cani=-2, monn=1}
postPointsMap={alsk=0, dwp=1, cani=0, monn=-1}
correct alsk from -2 -> 0
correct cani from -2 -> 0
correct dwp from 3 -> 1
correct monn from 1 -> -1
doTestCycle out.
doTestCycle enter
isIntense=false
initPointsMap={frmi=2, peeh=-2, alsk=0, cani=0}
postPointsMap={frmi=3, peeh=-3, alsk=1, cani=-1}
correct alsk from 0 -> 1
correct frmi from 2 -> 3
correct peeh from -2 -> -3
correct cani from 0 -> -1
doTestCycle out.
doTestCycle enter
isIntense=false
initPointsMap={frmi=3, alsk=1, dwp=1, cani=-1}
postPointsMap={frmi=4, alsk=0, dwp=0, cani=0}
correct frmi from 3 -> 4
correct cani from -1 -> 0
correct alsk from 1 -> 0
correct dwp from 1 -> 0
doTestCycle out.
doTestCycle enter
isIntense=true
initPointsMap={frmi=4, peeh=-3, dwp=0, cani=0}
postPointsMap={frmi=2, peeh=-1, dwp=-2, cani=2}
correct cani from 0 -> 2
correct peeh from -3 -> -1
correct frmi from 4 -> 2
correct dwp from 0 -> -2
doTestCycle out.
doTestCycle enter
isIntense=false
initPointsMap={frmi=2, peeh=-1, cani=2, monn=-1}
postPointsMap={frmi=1, peeh=0, cani=3, monn=-2}
correct cani from 2 -> 3
correct peeh from -1 -> 0
correct monn from -1 -> -2
correct frmi from 2 -> 1
doTestCycle out.
doTestCycle enter
isIntense=false
initPointsMap={frmi=1, peeh=0, cani=3, monn=-2}
postPointsMap={frmi=0, peeh=1, cani=4, monn=-3}
correct peeh from 0 -> 1
correct cani from 3 -> 4
correct frmi from 1 -> 0
correct monn from -2 -> -3
doTestCycle out.
doTestCycle enter
isIntense=false
initPointsMap={peeh=1, alsk=0, cani=4, monn=-3}
postPointsMap={peeh=2, alsk=1, cani=3, monn=-4}
correct alsk from 0 -> 1
correct peeh from 1 -> 2
correct monn from -3 -> -4
correct cani from 4 -> 3
doTestCycle out.
doTestCycle enter
isIntense=false
initPointsMap={frmi=0, alsk=1, dwp=-2, monn=-4}
postPointsMap={frmi=-1, alsk=2, dwp=-1, monn=-5}
correct dwp from -2 -> -1
correct alsk from 1 -> 2
correct monn from -4 -> -5
correct frmi from 0 -> -1
doTestCycle out.
doTestCycle enter
isIntense=false
initPointsMap={alsk=2, peeh=2, cani=3, dwp=-1}
postPointsMap={alsk=1, peeh=3, cani=2, dwp=0}
correct dwp from -1 -> 0
correct peeh from 2 -> 3
correct cani from 3 -> 2
correct alsk from 2 -> 1
doTestCycle out.
doTestCycle enter
isIntense=true
initPointsMap={frmi=-1, alsk=1, peeh=3, cani=2}
postPointsMap={frmi=-2, alsk=0, peeh=4, cani=3}

junit.framework.AssertionFailedError: WTF!!! peeh from 3 -> 4
    at dk.skov.nykredit.bf.TestSelenium.validateResult(TestSelenium.java:77)
    at dk.skov.nykredit.bf.TestSelenium.doTestCycle(TestSelenium.java:67)
    at dk.skov.nykredit.bf.TestSelenium.testOne(TestSelenium.java:36)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

Process finished with exit code -1

**Comment by tarcom** [comment]
Fixed in latest release: https://github.com/tarcom/NykreditBF/commit/ecf952e48472c685dc3aebed322ae8ce6d1a0114
